SWdaily/SWdaily/urls.py
from django.contrib import admin
from django.urls import path,include
from dailyreport.views import index_view
def i18n_javascript(request):
    return admin.site.i18n_javascript(request)
urlpatterns = [
    path(r'admin/jsi18n/',i18n_javascript),
    path(r'',index_view.index),
    path(r'dr/',include('dailyreport.urls')),
    path('admin/', admin.site.urls),
]

SWdaily/dailyreport/urls.py
from django.urls import path
#import views.index_view as index_view
from dailyreport.views import index_view,login_view,changepassword_view,main_view,user_view,project_view,report_view


app_name='dailyreport'

urlpatterns=[
        path(r'',index_view.index,name='index'),
               
        path(r'logout/',login_view.logout,name='logout'),
        path(r'login/',login_view.login,name='login'),
        path('login/changepwd/',changepassword_view.changePassword,name='changepassword'),
        path('main/',main_view.main,name='main'),
        path('project/',project_view.searchProject,name='project'),
        path('user/',user_view.searchUser,name='users'),
        path('adduser/',user_view.addUser,name='adduser'),
        path('addproject/',project_view.AddProject,name='addproject'),
        path('delproject/',project_view.DeleteProject,name='delproject'),
        path(r'report/',report_view.searchReport,name='report'),
        path(r'delreport/',report_view.DeleteReport,name='delreport'),
        ]

SWdaily/dailyreport/forms.py
from django import forms
from django.contrib.admin import widgets

class WriteReportForm(forms.Form):
    pub_date=forms.DateField(required=True,label="日期",widget=widgets.AdminDateWidget())

SWdaily/dailyreport/views/changepassword_view.py
# -*- coding:utf-8 -*-
from django.shortcuts import render,get_object_or_404
from dailyreport.models import Users
from django.contrib.auth.hashers import make_password
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse


def changePassword(request):
    if request.method=='GET':
        if request.session.get('is_login',False):
            return render(request,'dailyreport/changepassword.html',{
                'error_message':request.session['user_name'],})
        else:
            return HttpResponseRedirect(reverse('dailyreport:login'))
    if request .method=='POST':
        pwd1=request.POST['pwd1']
        pwd2=request.POST['pwd2']
        if pwd1!=pwd2:
            return render(request,'dailyreport/changepassword.html',{
                'error_message':'两次密码不一致',
                })
        else:
            userid=request.session['user_id']
            a=Users.objects.get(id=userid)
            a.password=make_password(pwd1)
            a.save()
            #TODO
            return HttpResponseRedirect(reverse('dailyreport:main'))

SWdaily/dailyreport/views/index_view.py
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
def index(request):
    return HttpResponseRedirect(reverse('dailyreport:main'))

SWdaily/dailyreport/views/login_view.py
# -*- coding:utf:8 -*-
from django.shortcuts import render,get_object_or_404
from dailyreport.models import Users
from django.contrib.auth.hashers import check_password
from django.urls import reverse
from django.http import HttpResponse,HttpResponseRedirect


def login(request):
    if request.method=='GET':
        return render(request,'dailyreport/login.html',{})
    if request.method=='POST':
        try:
            login_user=Users.objects.get(name=request.POST['username'])
        except (KeyError,Users.DoesNotExist):
            msg="没有此用户，请检查用户名"
            return render(request,'dailyreport/login.html',{
                'error_message':msg,
                })
        else:
            password=request.POST['pwd']
            if check_password(password,login_user.password):
                request.session['is_login']=True
                request.session['user_id']=login_user.id
                request.session['user_name']=login_user.name
                request.session['is_super']=login_user.superuser
                if password=="123456":
                    return render(request,'dailyreport/changepassword.html',{
                        'error_message':login_user.name,})
                else:
                    #TODO
                    return HttpResponseRedirect(reverse('dailyreport:main'))
            else:
                return render(request,'dailyreport/login.html',{
                    'error_message':'密码错误',})

def logout(request):
    request.session.clear()
    return HttpResponseRedirect(reverse('dailyreport:login'))

SWdaily/dailyreport/views/main_view.py
# -*- coding:utf-8 -*-
from django.shortcuts import render,get_object_or_404
from dailyreport.models import Users,Report,Project,UserToProject,ReportToProject
from dailyreport.forms import WriteReportForm
from django.http import HttpResponseRedirect,HttpResponse

from django.urls import reverse
from django.utils import timezone

def main(request):
    if request.method=='GET':
        if request.session.get('is_login',False):
            a=get_object_or_404(Users,id=request.session['user_id'])
            reportlist=Report.objects.filter(author=a).order_by('-pub_date')[:5]
            projectlist=Project.objects.filter(isWorking=True)
            form=WriteReportForm()
            return render(request,'dailyreport/main.html',{
                'user':a,'report_list':reportlist,
                'project_list':projectlist,
                'today':timezone.now(),
                'form':form,
                })
        else:
            return HttpResponseRedirect(reverse('dailyreport:login'))
    if request.method=='POST':
        a=get_object_or_404(Users,id=request.session['user_id'])
        pub_date=request.POST['pub_date']
        pro1_id=request.POST['project1']
        pro1_weight=request.POST['weight1']
        pro2_id=request.POST['project2']
        pro2_weight=request.POST['weight2']
        pro3_id=request.POST['project3']
        pro3_weight=request.POST['weight3']
        detail=request.POST['detail']
        sumOfWeight=float(pro1_weight)+float(pro2_weight)+float(pro3_weight)
        if sumOfWeight>1.0001 or sumOfWeight<0.99999:
            return HttpResponse("三个项目贡献之和不等于1，请返回重写")
        report,created=Report.objects.get_or_create(author=a,pub_date=pub_date)
        if not created:
            if float(report.weight1)>0:
                p1=Project.objects.get(name=report.project1)
                u2p1=UserToProject.objects.get(author=a,project=p1)
                u2p1.addWeight(-float(report.weight1))
                if u2p1.weight<=0:
                    u2p1.delete()
            if float(report.weight2)>0:
                p1=Project.objects.get(name=report.project2)
                u2p1=UserToProject.objects.get(author=a,project=p1)
                u2p1.addWeight(-float(report.weight2))
                if u2p1.weight<=0:
                    u2p1.delete()
            if float(report.weight3)>0:
                p1=Project.objects.get(name=report.project3)
                u2p1=UserToProject.objects.get(author=a,project=p1)
                u2p1.addWeight(-float(report.weight3))
                if u2p1.weight<=0:
                    u2p1.delete()
            ReportToProject.objects.filter(report=report).delete()

        p1=Project.objects.get(id=pro2_id)
        u2p1,c=UserToProject.objects.get_or_create(author=a,project=p1)
        u2p1.addWeight(float(pro2_weight))
        report.project2=str(p1)
        ReportToProject.objects.create(report=report,project=p1,weight=pro2_weight,author=a,pub_date=pub_date)

        p1=Project.objects.get(id=pro1_id)
        u2p1,c=UserToProject.objects.get_or_create(author=a,project=p1)
        u2p1.addWeight(float(pro1_weight))
        report.project1=str(p1)
        ReportToProject.objects.create(report=report,project=p1,weight=pro1_weight,author=a,pub_date=pub_date)

        p1=Project.objects.get(id=pro3_id)
        u2p1,c=UserToProject.objects.get_or_create(author=a,project=p1)
        u2p1.addWeight(float(pro3_weight))
        report.project3=str(p1)

        ReportToProject.objects.create(report=report,project=p1,weight=pro3_weight,author=a,pub_date=pub_date)
        report.detail=detail
        report.weight1=pro1_weight
        report.weight2=pro2_weight
        report.weight3=pro3_weight
        report.save()
        
        return HttpResponseRedirect(reverse('dailyreport:main'))

SWdaily/dailyreport/views/project_view.py
# -*- coding:utf:8 -*-
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from dailyreport.models import Users,Project,Report,UserToProject,ReportToProject
from django.shortcuts import render,get_object_or_404
from django.utils import timezone
import json

def searchProject(request):
    if not request.session.get('is_login',False):
        return HttpResponseRedirect(reverse('dailyreport:login'))

    project_list=Project.objects.all()
    p_list=[]
    for pro in project_list:
        p_list.append([pro.id,pro.name,pro.detail,str(pro.start_date),str(pro.end_date),pro.isWorking,pro.reward])

    if request.method=='GET':
        return_list=[]
        for p in project_list:
            p_user=[""]
            p_weight=[p.name]
            u2p_list=UserToProject.objects.filter(project=p)
            sumOfWeight=0
            for u2p in u2p_list:
                sumOfWeight+=u2p.weight
                p_user.append(str(u2p.author))
                p_weight.append('%.1f'%u2p.weight)
            p_user.append("合计")
            p_weight.append('%.1f'%sumOfWeight)
            return_list.append([p_user,p_weight])
        return render(request,'dailyreport/project.html',{
            'user':request.session['user_name'],
            'return_list':return_list,
            'today':timezone.now(),
            'project_list':project_list,
            'is_super':request.session['is_super'],
            'p_list':json.dumps(p_list),
            })

    if request.method=='POST':
        project_id=request.POST['project']
        begin_date=request.POST['begin_date']
        end_date=request.POST['end_date']
        temp=[]
        if project_id=="-1":
            temp=project_list.filter(isWorking=True)
        elif project_id=="-2":
            temp=project_list.filter(isWorking=False)
        else:
            temp=[Project.objects.get(id=project_id)]
        return_list=[]
        for project in temp:
            element=GetReturnElement(project,begin_date,end_date)
            if element!=None:
                return_list.append(element)
        return render(request,'dailyreport/project.html',{
            'user':request.session['user_name'],
            'return_list':return_list,
            'today':timezone.now(),
            'project_list':project_list,
            'is_super':request.session['is_super'],
            'p_list':json.dumps(p_list),
            })

def GetReturnElement(project,begin_date,end_date):
    if begin_date=="":
        begin_date="2015-05-24"
    if end_date=="":
        end_date=timezone.now()
    r2p_list=ReportToProject.objects.filter(project=project,pub_date__gte=begin_date,pub_date__lte=end_date)
    user_dict={}
    for r2p in r2p_list:
        user_dict[r2p.author]=0.0
    sumOfWeight=0.0
    for r2p in r2p_list:
        sumOfWeight+=r2p.weight
        user_dict[r2p.author]+=r2p.weight
    if len(user_dict)==0:
        return None
    p_user=[""]
    p_weight=[project.name]
    for key,value in user_dict.items():
        p_user.append(key)
        p_weight.append('%.1f'%value)
    p_user.append("合计")
    p_weight.append('%.1f'%sumOfWeight)
    return [p_user,p_weight]

def AddProject(request):
    if not request.session['is_login']:
        return HttpResponseRedirect(reverse('dailyreport:login'))
    if request.method=='GET':
        return HttpResponseRedirect(reverse('dailyreport:project'))

    if request.method=='POST':
        pro_id=request.POST['project']
        pro_name=request.POST['projectname']
        pro_detail=request.POST['projectdetail']
        begin_date=request.POST['begin_date']
        end_date=request.POST['end_date']
        pro_isWorking=request.POST['isworking']=="1"
        pro_reward=request.POST['reward']
        pro=""
        if pro_id=="-1":
            pro,created=Project.objects.get_or_create(name=pro_name)
            if not created:
                return HttpResponse("已存在同名项目，请修改项目名称")
        else:
            pro=Project.objects.get(id=pro_id)
            
            if pro.name!=pro_name:
                try:
                    Project.objects.get(name=pro_name)
                    return HttpResponse("已存在同名项目")
                except:
                    pro.name=pro_name
        pro.detail=pro_detail
        pro.start_date=begin_date
        pro.end_date=end_date
        pro.isWorking=pro_isWorking
        pro.reward=pro_reward
        pro.save()
        if pro_id=="-1":
            return HttpResponse("创建项目成功")
        else:
            return HttpResponse("修改项目成功")

def DeleteProject(request):
    if not request.session['is_login']:
        return HttpResponseRedirect(reverse('dailyreport:login'))
    if request.method=='GET':
        return render(request,'dailyreport/testdate.html',{})
        return HttpResponseRedirect(reverse('dailyreport:project'))
    if request.method=='POST':
        pro_id=request.POST["project"]
        pro=Project.objects.get(id=pro_id)
        name=pro.name
        ReportToProject.objects.filter(project=pro).delete()
        UserToProject.objects.filter(project=pro).delete()
        pro.delete()
        return HttpResponse(name+"已被删除")

SWdaily/dailyreport/views/report_view.py
# -*- coding:utf-8 -*-
from django.shortcuts import render,get_object_or_404
from dailyreport.models import Users,Report,Project,UserToProject,ReportToProject
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.utils import timezone

def searchReport(request):
    if not request.session.get('is_login',False):
        return HttpResponseRedirect(reverse('dailyreport:login'))
    if request.method=='GET':
        userlist=Users.objects.filter(active=True)
        a=get_object_or_404(Users,id=request.session['user_id'])
        reportlist=Report.objects.filter(author=a).order_by('pub_date')[:30]
        return render(request,'dailyreport/report.html',{
            'user':a,
            'report_list':[[a,reportlist]],
            'user_list':userlist,
            'today':timezone.now(),
            'is_super':request.session['is_super'],
            })
    if request.method=='POST':
        return_list=[]
        user_id=request.POST['user']
        if user_id=="-1":
            users=Users.objects.filter(active=True)
            for u in users:
                return_list.append([u])
        else:
            u=Users.objects.get(id=user_id)
            return_list.append([u])
        begin_date=request.POST['begin_date']
        end_date=request.POST['end_date']
        for rp in return_list:
            if begin_date=="":
                begin_date="2015-05-24"
            if end_date=="":
                end_date=timezone.now()
            reportlist=Report.objects.filter(author=rp[0],pub_date__gte=begin_date,pub_date__lte=end_date)
            rp.append(reportlist)

        return render(request,'dailyreport/report.html',{
            'user':request.session['user_name'],
            'report_list':return_list,
            'user_list':Users.objects.filter(active=True),
            'today':timezone.now(),
            'is_super':request.session['is_super'],
            })

def DeleteReport(request):
    if not request.session.get('is_login',False):
        return HttpResponseRedirect(reverse('dailyreport:login'))
    if request.method=='GET':
        return HttpResponseRedirect(reverse('dailyreport:report'))
    if request.method=='POST':
        try:
            a=Users.objects.get(id=request.POST['user'])
            date=request.POST['del_date']
            report=Report.objects.get(author=a,pub_date=date)
            if float(report.weight1)>0:
                p1=Project.objects.get(name=report.project1)
                u2p1=UserToProject.objects.get(author=a,project=p1)
                u2p1.addWeight(-float(report.weight1))
                if u2p1.weight<=0:
                    u2p1.delete()
            if float(report.weight2)>0:
                p1=Project.objects.get(name=report.project2)
                u2p1=UserToProject.objects.get(author=a,project=p1)
                u2p1.addWeight(-float(report.weight2))
                if u2p1.weight<=0:
                    u2p1.delete()
            if float(report.weight3)>0:
                p1=Project.objects.get(name=report.project3)
                u2p1=UserToProject.objects.get(author=a,project=p1)
                u2p1.addWeight(-float(report.weight3))
                if u2p1.weight<=0:
                    u2p1.delete()
            ReportToProject.objects.filter(report=report).delete()
            report.delete()
            return HttpResponse("员工"+a.name+"的"+date+"日报已被删除")
        except:
            return HttpResponse("无法查询到此日报，请检查输入")

SWdaily/dailyreport/templates/dailyreport/changepassword.html
<!DOCTYPE html>
<html>
<head>
	<title>修改密码</title>
	<meta charset="utf-8">
		<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
		<link rel="stylesheet" type="text/css" href="/static/admin/css/login.css">
	<script>
		function validForm()
		{
			var f=document.forms['changepwd'];
			var pwd1=f['pwd1'].value;
			var pwd2=f['pwd2'].value;
			if(pwd1==null || pwd1=="" || pwd2==null ||pwd2=="")
			{
				alert("密码不能为空");
				return false;
			}
		}

	</script>
</head>
<body class="login" data-admin-utc-offset="28800">
	<div id="container">
		<div id="header">
			<div id="branding">
				<h1>请修改密码</h1>
			</div>
		</div>
		<div id="content" class="colM">
			{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
			<div id="content-main">
				<form name="changepwd" action="{% url 'dailyreport:changepassword' %}" onsubmit="return validForm()" method="post">
					{% csrf_token %}
					<div class="form-row">
						<label class="required" for="id_pwd1">新密码:</label>
						<input type="password" name="pwd1" required id="id_pwd1"><br>
						<label class="required" for="id_pwd2">确认密码:</label>
						<input type="password" name="pwd2" id="id_pwd2" required>
					</div>
					<div class="submit-row">
					<input type="submit" value="提交">
					</div>
				</form>
			</div>
		</div>
	</div>

</body>
</html>

SWdaily/dailyreport/templates/dailyreport/detail.html
<h1>{{user}}</h1>
<ul>
	<li>'name:'{{user.name}}</li>
	<li>{{user.id}}</li>
	<li>{{user.userid}}</li>
	<li>{{user.last_login_time}}</li>
</ul>

SWdaily/dailyreport/templates/dailyreport/project.html
<!DOCTYPE html>
<html>
<head>
	<title>项目</title>
	<meta charset="utf-8">
	{% load static %}

	<link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
	
	<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
	
	
	<script type="text/javascript" src="/admin/jsi18n/"></script>
	<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
	<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
	<script type="text/javascript" src="/static/admin/js/core.js"></script>

	<script type="text/javascript" src="/static/admin/js/calendar.js"></script>
	<script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
	<script>
		function ChangeProject()
		{
			var f=document.forms['addproject'];
			var pro_id=f['project'].value;
			var list={{p_list|safe}};
			for (pro in list)
			{
				if(list[pro][0]==pro_id)
				{
					f['projectname'].value=list[pro][1];
					f['projectdetail'].value=list[pro][2];
					f['begin_date'].value=list[pro][3];
					f['end_date'].value=list[pro][4];
					if(list[pro][5])
					{
						f['isworking'][0].checked=true;
					}
					else
					{
						f['isworking'][1].checked=true;
					}
					f['reward'].value=list[pro][6];

				}
			}
		}
		function CheckAddProject()
		{
			var f=document.forms['addproject'];
			if(f['projectname'].value==null || f['projectname'].value=="")
			{
				alert("项目名称不能为空");
				return false;
			}
			if(f['begin_date'].value==null || f['begin_date'].value=="" || f['end_date'].value==null || f['end_date'].value=="")
			{
				alert("请填写项目起止日期");
				return false;
			}
			if(f['reward']==null || f['reward']=="")
			{
				alert("请填写项目提成");
				return false;
			}
		}
		function Searchpro(doing)
		{
			var f=document.forms["search"];
			if(doing)
			{
				f["project"].value=f["projectdoing"].value;
			}
			else
			{
				f["project"].value=f["projectdone"].value;
			}
			//alert(f["project"].value);
			f.submit();
		}
	</script>
</head>
<body>
	<div id="header">
		<div id="branding">
			<h1>杭州书微信息技术有限公司动画部项目管理系统</h1>
		</div>
		<div id="user-tools">
			<strong>{{user}}</strong>
			<a href="{% url 'dailyreport:changepassword' %}">修改密码</a>
			,
			<a href="{% url 'dailyreport:logout' %}">登出</a>
		</div>
	</div>
<ul class="daohanglan">
	<li class="daohanglan">
	<a href="{% url 'dailyreport:main' %}">写日报</a>
	</li>
	<li class="daohanglan"><a href="{% url 'dailyreport:report' %}">日报查询</a></li>
	<li class="daohanglan"><a href="{% url 'dailyreport:users' %}">用户查询</a></li>
	<li class="daohanglan"><a href="{% url 'dailyreport:project' %}" class="active" >项目查询</a></li>
</ul>
<div id="content" class="colM">
<h2>项目查询</h2>

<form id="search" action="{% url 'dailyreport:project' %}" method="post">
	{% csrf_token %}
	<label>进行中的项目</label><select name="projectdoing">
		<option value=-1>全部</option>
		{% for p in project_list %}
		{% if p.isWorking %}
		<option value={{p.id}}>{{p.name}}</option>
		{% endif %}
		{% endfor %}
	</select>
	<label>完结的项目</label><select name="projectdone">
		<option value=-2>全部</option>
		{% for p in project_list %}
		{% if not p.isWorking %}
		<option value={{p.id}}>{{p.name}}</option>
		{% endif %}
		{% endfor %}
	</select>
	<input type="hidden" name="project">
	<br>
	<label>起始日期</label><input type="text" name="begin_date" value={{today|date:"Y-m-d"}} class="vDateField" size="10">
	<br>
	<label>结束日期</label><input type="text" name="end_date" value={{today|date:"Y-m-d"}} class="vDateField" size="10">
	<br>
	<input type="button" value="查询" onclick='Searchpro(true)'>
	<input type="button" value="查询完结项目" onclick='Searchpro(false)'>
</form>
<br><br><br>
{% for project in return_list %}
<table border="2">
	<tr>
		{% for user in project.0 %}
		<th>{{user}}</th>
		{% endfor %}
	</tr>
	<tr>
		{% for weight in project.1 %}
		<td>{{weight}}</td>
		{% endfor %}
	</tr>
</table>
<br>
{% endfor %}
{% if is_super %}
<h2>你好，管理员</h2>
<p>添加新项目/修改旧项目</p>
<form onsubmit="return CheckAddProject()" name="addproject" action="{% url 'dailyreport:addproject' %}" method="post">
	{% csrf_token %}
	<label>项目名称</label><select name="project" onchange="ChangeProject()">
		<option value=-1>新项目</option>
		{% for p in project_list %}
		<option value={{p.id}}>{{p.name}}</option>
		{% endfor %}
	</select>
	<input type="text" name="projectname"><br>
	<label>项目描述</label><textarea name="projectdetail" cols="35" row="5" maxlength="250"></textarea><br>
	<label>启动日期</label><input type="text" name="begin_date" class="vDateField" size="10"><br>
	<label>完结日期</label><input type="text" name="end_date" class="vDateField" size="10"><br>
	<p>是否完结？（完结的项目，员工在日报里无法贡献）</p>
	<p><input type="radio" name="isworking" value="1" checked >正在进行中</p>
	<p><input type="radio" name="isworking" value="0" >已完结</p>
	<label>提成</label><input type="number" name="reward" min=0 >
	<br>
	<input type="submit" value="提交">
</form>
	<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<form name="delproject" action="{% url 'dailyreport:delproject' %}" method="post">
	{% csrf_token %}
	<label>项目名称</label><select name="project">
		{% for p in project_list %}
		<option value={{p.id}}>{{p.name}}</option>
		{% endfor %}
	</select>
	<input type="submit" value="删除">
</form>
{% endif %}
</div>
</body>
</html>

SWdaily/dailyreport/templates/dailyreport/report.html
<!DOCTYPE html>
<html>
<head>
	<title>查询日报</title>
	<meta charset="utf-8">
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
	
	<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
	
	
	<script type="text/javascript" src="/admin/jsi18n/"></script>
	<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
	<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
	<script type="text/javascript" src="/static/admin/js/core.js"></script>

	<script type="text/javascript" src="/static/admin/js/calendar.js"></script>
	<script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
</head>
<body>
	<div id="header">
		<div id="branding">
			<h1>杭州书微信息技术有限公司动画部项目管理系统</h1>
		</div>
		<div id="user-tools">
			<strong>{{user}}</strong>
			<a href="{% url 'dailyreport:changepassword' %}">修改密码</a>
			,
			<a href="{% url 'dailyreport:logout' %}">登出</a>
		</div>

	</div>
<ul class="daohanglan">
	<li class="daohanglan">
	<a href="{% url 'dailyreport:main' %}" >写日报</a>
	</li>
	<li class="daohanglan"><a href="{% url 'dailyreport:report' %}" class="active">日报查询</a></li>
	<li class="daohanglan"><a href="{% url 'dailyreport:users' %}">用户查询</a></li>
	<li class="daohanglan"><a href="{% url 'dailyreport:project' %}">项目查询</a></li>
</ul>

	<div id="content" class="colM">
	<form action="{% url 'dailyreport:report' %}" method="post">
	{% csrf_token %}
	<label>员工</label><select name="user">
		<option value=-1>全部</option>
		{% for u in user_list %}
		<option value={{u.id}}>{{u.name}}</option>
		{% endfor %}
	</select>
	<br>
	<label>起始</label><input type="text" name="begin_date" value={{today|date:"Y-m-d"}} class="vDateField" size="10">   
	<br>
	<label>结束</label><input type="text" name="end_date" value={{today|date:"Y-m-d"}} class="vDateField" size="10">
	<br>

	<input type="submit" value="查询">
	</form>
	{% for rp in report_list %}
	<h2>{{rp.0}}</h2>
	{% if rp.1 %}
	<table border="2">
		<tr>
			<th>日期</th>
			<th>项目1</th>
			<th>贡献</th>
			<th>项目2</th>
			<th>贡献</th>
			<th>项目3</th>
			<th>贡献</th>
			<th>描述</th>
		</tr>
		{% for report in rp.1 %}
		<tr>
			<td>{{report.pub_date}}</td>
			<td>{{report.project1}}</td>
			<td>{{report.weight1}}</td>
			<td>{{report.project2}}</td>
			<td>{{report.weight2}}</td>
			<td>{{report.project3}}</td>
			<td>{{report.weight3}}</td>
			<td>{{report.detail}}</td>
		</tr>
		{% endfor %}
	</table>
	{% else %}
	<p>没有查询到日报</p>
	{% endif %}
	{% endfor %}
	</div>
	<br><br><br>
	{% if is_super %}
	<p>您好，管理员</p>
	<form id='der' method='post' action="{% url 'dailyreport:delreport' %}">
	{% csrf_token %}
		<label>员工</label><select name="user">
			{% for u in user_list %}
			<option value={{u.id}}>{{u.name}}</option>
			{% endfor %}
		</select>
		<label>日期</label><input type="text" name="del_date" value={{today|date:"Y-m-d"}} class="vDateField" size="10">   
		<input type='submit' value="删除日报">
	</form>
	{% endif %}
</body>
</html>